# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    working_directory: ~/project/TestingActivity
    docker:
      - image: circleci/node:8 #cimg/node:15.8.0 # buildpack-deps:trusty
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run test

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  testingactivity:
    # Run the welcome/run job in its own container
    jobs:
      - test
